### ISSUE TITLE
Rebranding to Social Economy Data Lab

### ISSUE THREAD

**Issue by rorads** [SocialInvestmentDataLab/spec#32]
This project in now referred to as the social economy data lab, rather than the social investment data lab. This still needs to be implemented throughout the copy, templates, code, and hyperlinks.

**Comment by rorads** [comment]
Pull request added here: https://github.com/SocialEconomyDataLab/spec/pull/33

Assigning to @timgdavies for review and merge

**Comment by ScatteredInk** [comment]
Completed with #33
